### ISSUE TITLE
Is there a 3.5 version of dtnperf which supports ibr-dtn?

### ISSUE THREAD

**Issue by diogosm** [michirod/dtnperf#4]
Hello,

I saw this document [pdf](http://cnrl.deis.unibo.it/download/DTNperf_3_Guide_v3.5.0.pdf). The authors presented a release notes about new features of 3.5 dtnperf version. Any support about this nowadays?

My best regards,

**Comment by michirod** [comment]
Hi, 
the latest released version is available with the ION-DTN package. It has IBR-DTN support.
https://sourceforge.net/projects/ion-dtn/files/latest/download

Yes, I should update this repository...

**Comment by diogosm** [comment]
Thank you ^^ :smile:
